name: puntajepro
description: Aplicación Flutter para preparación Saber 11 ICFES con plan diario, simulacros y modo offline.
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.6
  firebase_crashlytics: ^3.5.6
  google_sign_in: ^6.1.5
  in_app_purchase: ^3.1.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/seed/questions.json
